### ISSUE TITLE
Javascript API: CORS error

### ISSUE THREAD

**Issue by CS76** [berlinguyinca/spectra-hash#15]
Hi, 

I was trying to use your REST service to generate the spectral hash. But it does'nt allow cross origin request. Can you please include the CORS header on your server side implementation.

Looking forward for your response.
Thank u.

-Chandu

**Comment by benn7** [comment]
Thanks for notifying us Chandu. I'll take a look into the issue.

**Comment by berlinguyinca** [comment]
Dear Chandu,

we will look into this and it should be fixed in the next couple of days. Could you please provide us with further information, which urls exactly you are calling etc?

@benn7 is it working from your remote location? Just want to make sure it's not an IP Address filter on the firewall level, which prevents this.

**Comment by CS76** [comment]
Hi,

Thank you for your prompt response.

I am querying (POST request) to this url - http://splash.fiehnlab.ucdavis.edu/
Infact I am just using your javascript funtion to ajax call the above url. The request is blocked because of the CORS issue. I have tried disabling CORS in my browser and it work fine then. 

Since the request is not from the same domain its rejecting the request. Allowing cross origin request in the header should fix this.

Once again thank you for your response.

**Comment by berlinguyinca** [comment]
Ok we discovered what is causing this and this should be fixed in about
90-120 minutes. I just need to redeploy the server and apply the changes. I
let you know when it's back online so you can test.

g.

On Tue, Jan 19, 2016 at 7:53 AM, Venkata Chandrasekhar Nainala <
notifications@github.com> wrote:

> Hi,
>
> Thank you for your prompt response.
>
> I am querying (POST request) to this url -
> http://splash.fiehnlab.ucdavis.edu/
> Infact I am just using your javascript funtion to ajax call the above url.
> The request is blocked because of the CORS issue. I have tried disabling
> CORS in my browser and it work fine then.
>
> Since the request is not from the same domain its rejecting the request.
> Allowing cross origin request in the header should fix this.
>
> Once again thank you for your response.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/berlinguyinca/spectra-hash/issues/15#issuecomment-172896088>
> .
>



-- 
------------------------------------------------------------
Lead Developer - Fiehnlab, UC Davis

gert wohlgemuth

work:
http://fiehnlab.ucdavis.edu/staff/wohlgemuth

phone:
530 665 9477

coding blog:
http://codingandmore.blogspot.com

linkedin:
http://www.linkedin.com/profile/view?id=28611299&trk=tab_pro

**Comment by CS76** [comment]
Sure, thank you @berlinguyinca 

- Chandu

**Comment by rsalek** [comment]
@berlinguyinca our plan is to test/try it in MetaboLights
