### ISSUE TITLE
Java library not compatible with Java 7

### ISSUE THREAD

**Issue by tomas-pluskal** [berlinguyinca/spectra-hash#26]
Hi,
It seems the Java (Scala) classes deployed to the Fiehn lab's maven repository are compiled with Java 8 as target version. Is there any reason for that? Could you change it to Java 7 and release an updated version?
Thanks,
Tomas

**Comment by berlinguyinca** [comment]
Dear all

Sorry we stopped supporting java 7 a while ago. Could you just wrap the
rest api. If you really need 7 support?

Thanks
G.

**Comment by tomas-pluskal** [comment]
It is for MSDK, which is declared as Java 7-friendly. Using the REST API is not practical for MSDK.

If no Java 8-specific API is used in the SPLASH code, wouldn't it be a matter of just changing one entry in the pom.xml?

**Comment by berlinguyinca** [comment]
The problem is that the patent pom of the splash is used in dozens of other
projects and so we can't just change it. I look a bit more into it next
week. If we can adjust it.

G.
On May 14, 2016 4:44 PM, "Tomáš Pluskal" <notifications@github.com> wrote:

It is for MSDK, which is declared as Java 7-friendly. Using the REST API is
not practical for MSDK.

If no Java 8-specific API is used in the SPLASH code, wouldn't it be a
matter of just changing one entry in the pom.xml?

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/berlinguyinca/spectra-hash/issues/26#issuecomment-219257766>

**Comment by tomas-pluskal** [comment]
It is possible to override the child pom's java version without modifying the parent. See here: http://stackoverflow.com/questions/1771561/maven-is-it-possible-to-override-the-configuration-of-a-plugin-already-defined

**Comment by berlinguyinca** [comment]
Would you like todo this? I think you have commit rights.

G.

**Comment by tomas-pluskal** [comment]
Sure! I'll send a pull request.

**Comment by tomas-pluskal** [comment]
See PR #27
