### ISSUE TITLE
Possible hash mismatch?

### ISSUE THREAD

**Issue by egonw** [berlinguyinca/spectra-hash#29]
Fwd from @johnmay on G+: https://plus.google.com/u/0/+JohnMay/posts/3kTdkBhripx?sfc=true 

    "Sounds neat... but just found this on HMDB on first try. Others do hash to
    the same so it does work just maybe has false negatives which is undesirable
    for a hashcode (FP=Okay)?
    
    Spectrum in HMDB: http://www.hmdb.ca/spectra/c_ms/2161
    Spectrum in MONA: http://mona.fiehnlab.ucdavis.edu/spectra/display/HMDB00010_2161
    
    [...]"

It's for the same compound, looks like the same spectrum, but different splashes...

**Comment by ssmehta** [comment]
Thanks for passing this along, Egon.  This seems to be due to the fact that HMDB retains 0 intensity fragments, whereas MoNA removes upon importing.  I had forgotten we had decided to retain these fragments when computing the SPLASH.

For the sake of keeping the SPLASH consistent, we will also store zero ions in MoNA.  I'll have this updated tomorrow.

**Comment by ssmehta** [comment]
HMDB spectra have been updated, and the SPLASHes now match between HMDB and MoNA.  I've also verified that none of our other data sources include zero-intensity ions.
